### ISSUE TITLE
Episode Appears in The "Past" Tab When It Hasn't Aired yet

### ISSUE THREAD

**Issue by alexbooker** [MacKentoch/jsair-mobile#1]
At the time of this writing it's currently **11am (GMT) on the 11th of May**. 

The episode entitled _"The Science of People in Tech"_ doesn't air for another few hours yet it appears in the "Past" tab:

![](https://i.imgur.com/rtrbQ6O.png)

**Comment by MacKentoch** [comment]
Thank you @alexbooker  👍 

I located this 🐛 [here](https://github.com/MacKentoch/jsair-mobile/blob/master/ReactNativeApp/common/redux/actions/episodes.js#L100)

How did I missed that: 
```javascript
// bug in past episodes filter
function filterFuturEpisodes(allEpisode) {
  return allEpisode.filter(episode => isFuture(moment(episode.date).format('YYYY-MM-DD')));
}
```

Will be fixed (later — when back home — I will submit to stores apple and android) with: 
```javascript 
function filterPastEpisodes(allEpisode) {
  return allEpisode.filter(
    episode => {
      return  isPast(moment(episode.date).format('YYYY-MM-DD')) &&
              !isToday(moment(episode.date).format('YYYY-MM-DD'));
    }
  );
}
```

**Comment by MacKentoch** [comment]
### Fixed:
- **android** 
  - `v1.0.3` (*in store now so you should have an update notification soon*)
- **iOS**
  - `v1.0.1` (*in review now should come soon*)

> I will close the issue when fully released in all platforms.

#### Note: Why android, iOS and github version aren't the same?

1 - **Each platform is different and that is  a good thing!**
*Despite React Native makes code refactoring possible you can't have a 100% same code for all platform. Even if it were possible it would not be as nice as it would seem.*

2 - **Maybe I will have to update one platform and not another one (it has already been the case during beta tests pre first release).**

#### On conclusion 
> Thank you for submitting issue 👍 it helps so much

**Comment by alexbooker** [comment]
Awesome :smile:
