### ISSUE TITLE
Prepare for missing Hangout ID

### ISSUE THREAD

**Issue by kentcdodds** [MacKentoch/jsair-mobile#3]
With recent changes to how Hangouts on Air works, there will no longer be a `hangoutId` as part of the show data. I think the only thing you'll need to do is update the "Add to Calendar" button to use a new property (I'm working on now) called `calendarUrl`. I'll let you know when it's live.

**Comment by MacKentoch** [comment]
Hi @kentcdodds,

Thank you for taking time sharing news on this update.

When I heard about leaving hangout ([here](https://github.com/javascriptair/site/issues/147)) I first wondered whether I would be able to keep **add calendar button** (*useful button that I use each JS Air episode: since faster than opening youtube app and search for episode*).

Waiting for more information.
It will be occasion to upgrade React Native to latest version (*I planed to wait for Android Nougat and iOS 10 for that but it can be sooner to be sure to keep add To calendar functionality*).

**Comment by kentcdodds** [comment]
Alrighty changes are complete. I probably could have done this more gracefully, but there is no longer a `hangoutId` available on episodes anymore. Please link to the `calendarUrl` property instead.

**Comment by MacKentoch** [comment]
Nice, I will update as fast as possible.

It won't break the app, button will just disappear since looking for missing prop`hangoutUrl`.

Thank you I will give a feedback when new versions are in stores (*android submission is a matter of couple of hours by iOS can be a matter of days*).

**Comment by MacKentoch** [comment]
I guess I won't upgrade RN version this time since I encounter lots of issues like [this one](https://productpains.com/post/react-native/listview-doesnt-render-rows-until-scroll).

**Comment by MacKentoch** [comment]
I'm afraid I have no solution for iOS to access Google calendar.

- from JS air app: 
    - iOS Safari: it throws error `multiple redirection` (*I guess iOS Safari is misinterpreting with iCloud calendar...*)
- from javascript air website: 
   -  iOS Safari throws the same error

Problem is: in iOS dev can't force alternative navigator to open a link...

**Comment by kentcdodds** [comment]
How disappointing! If you come up with any solution and need anything from me, let me know.

**Comment by MacKentoch** [comment]
Alright I found the fix.

iOS Safari is tricky, when this error occur:
 - clear cache 
 - ensure cookies are enabled

I will show a gif for the explanations (*even for me in case I forget about it* 😄)

Let's publish 🎉 !

**Comment by MacKentoch** [comment]
`Add to calendar` is now back in JS Air app and both **iOS** and **android**:
- v1.0.4 android [playStore link](https://play.google.com/store/apps/details?id=com.jsair) 
- v1.0.2 iOS [appStore link](https://itunes.apple.com/fr/app/js-air/id1112141070?mt=8)



*Special note to iOS:*

If calendar link give `to many redirection error` on **safari** then follow explanations [here](https://github.com/MacKentoch/jsair-mobile#current-versions) 
- to clear safari data 
- and ensure cookies are enabled in safari.

Thanks to @kentcdodds for JS Air and help ! Just amazing to be able to so many thing.

> I'm feeling Impatient for JS air today show about very interesting subject *typed javascript*!

**Comment by kentcdodds** [comment]
Thank you!
